
services:
  cerbos:
    image: ghcr.io/cerbos/cerbos:latest
    container_name: cerbos

    restart: unless-stopped

    command: server --config=/config/config.yaml

    ports:
      - "3592:3592"
      - "3593:3593"

    volumes:
      - ./config:/config
      - ./policies:/policies
