"""move employee user relationship

Revision ID: 5f251f9bfc16
Revises: 
Create Date: 2026-05-16 19:25:33.997882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f251f9bfc16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'terminated', 'suspended', name='employee_status'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('terminated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='hris'
    )
    op.create_index(op.f('ix_hris_employees_employee_number'), 'employees', ['employee_number'], unique=True, schema='hris')
    op.create_index(op.f('ix_hris_employees_id'), 'employees', ['id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_employees_joined_at'), 'employees', ['joined_at'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_employees_status'), 'employees', ['status'], unique=False, schema='hris')
    op.create_table('organization_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('subscription_plan', sa.String(length=50), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hris'
    )
    op.create_index(op.f('ix_hris_organization_groups_code'), 'organization_groups', ['code'], unique=True, schema='hris')
    op.create_index(op.f('ix_hris_organization_groups_id'), 'organization_groups', ['id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_organization_groups_is_active'), 'organization_groups', ['is_active'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_organization_groups_status'), 'organization_groups', ['status'], unique=False, schema='hris')
    op.create_table('employee_sensitive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('marital_status', sa.String(), nullable=True),
    sa.Column('number_of_children', sa.Integer(), nullable=True),
    sa.Column('identity_id', sa.String(), nullable=True),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('social_security_id', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['hris.employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id'),
    schema='hris'
    )
    op.create_index(op.f('ix_hris_employee_sensitive_email'), 'employee_sensitive', ['email'], unique=True, schema='hris')
    op.create_index(op.f('ix_hris_employee_sensitive_id'), 'employee_sensitive', ['id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_employee_sensitive_identity_id'), 'employee_sensitive', ['identity_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_employee_sensitive_marital_status'), 'employee_sensitive', ['marital_status'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_employee_sensitive_number_of_children'), 'employee_sensitive', ['number_of_children'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_employee_sensitive_social_security_id'), 'employee_sensitive', ['social_security_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_employee_sensitive_tax_id'), 'employee_sensitive', ['tax_id'], unique=False, schema='hris')
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'trial', 'archived', name='organization_status'), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['hris.organization_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='hris'
    )
    op.create_index(op.f('ix_hris_organizations_code'), 'organizations', ['code'], unique=True, schema='hris')
    op.create_index(op.f('ix_hris_organizations_group_id'), 'organizations', ['group_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_organizations_id'), 'organizations', ['id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_organizations_is_deleted'), 'organizations', ['is_deleted'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_organizations_status'), 'organizations', ['status'], unique=False, schema='hris')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zitadel_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['hris.employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_id'),
    schema='hris'
    )
    op.create_index(op.f('ix_hris_users_zitadel_id'), 'users', ['zitadel_id'], unique=True, schema='hris')
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['hris.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hris'
    )
    op.create_index(op.f('ix_hris_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_audit_logs_id'), 'audit_logs', ['id'], unique=False, schema='hris')
    op.create_table('employee_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['hris.employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['hris.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'organization_id', name='uq_employee_org'),
    schema='hris'
    )
    op.create_table('employees_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['hris.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='hris'
    )
    op.create_index(op.f('ix_hris_employees_position_id'), 'employees_position', ['id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_employees_position_is_active'), 'employees_position', ['is_active'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_employees_position_organization_id'), 'employees_position', ['organization_id'], unique=False, schema='hris')
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['hris.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='hris'
    )
    op.create_index(op.f('ix_hris_invitations_email'), 'invitations', ['email'], unique=False, schema='hris')
    op.create_table('leave_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('requires_attachment', sa.Boolean(), nullable=False),
    sa.Column('max_days_per_year', sa.Integer(), nullable=True),
    sa.Column('max_consecutive_days', sa.Integer(), nullable=True),
    sa.Column('carry_forward_allowed', sa.Boolean(), nullable=False),
    sa.Column('carry_forward_limit', sa.Integer(), nullable=True),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['hris.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='hris'
    )
    op.create_index(op.f('ix_hris_leave_types_code'), 'leave_types', ['code'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_leave_types_id'), 'leave_types', ['id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_leave_types_is_active'), 'leave_types', ['is_active'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_leave_types_organization_id'), 'leave_types', ['organization_id'], unique=False, schema='hris')
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='membership_role_enum'), nullable=False),
    sa.Column('invited_by_id', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_id'], ['hris.users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['hris.organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['hris.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_org'),
    schema='hris'
    )
    op.create_index(op.f('ix_hris_memberships_is_active'), 'memberships', ['is_active'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_memberships_organization_id'), 'memberships', ['organization_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_memberships_role'), 'memberships', ['role'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_memberships_user_id'), 'memberships', ['user_id'], unique=False, schema='hris')
    op.create_table('offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('offices_type', sa.Enum('hq', 'branch', 'remote', 'warehouse', name='office_type_enum'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['hris.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['hris.offices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hris'
    )
    op.create_index(op.f('ix_hris_offices_code'), 'offices', ['code'], unique=True, schema='hris')
    op.create_index(op.f('ix_hris_offices_id'), 'offices', ['id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_offices_is_active'), 'offices', ['is_active'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_offices_offices_type'), 'offices', ['offices_type'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_offices_organization_id'), 'offices', ['organization_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_offices_parent_id'), 'offices', ['parent_id'], unique=False, schema='hris')
    op.create_table('employment_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employees_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('offices_id', sa.Integer(), nullable=False),
    sa.Column('manager_employment_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'terminated', 'suspended', name='employment_status'), nullable=False),
    sa.Column('employment_type', sa.Enum('permanent', 'contract', 'intern', name='employment_type'), nullable=True),
    sa.Column('position_snapshot', sa.String(), nullable=True),
    sa.Column('offices_snapshot', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employees_id'], ['hris.employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_employment_id'], ['hris.employment_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offices_id'], ['hris.offices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['hris.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['hris.employees_position.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employees_id', 'organization_id', name='uq_employee_org_employment'),
    schema='hris'
    )
    op.create_index(op.f('ix_hris_employment_models_employees_id'), 'employment_models', ['employees_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_employment_models_id'), 'employment_models', ['id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_employment_models_manager_employment_id'), 'employment_models', ['manager_employment_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_employment_models_organization_id'), 'employment_models', ['organization_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_employment_models_status'), 'employment_models', ['status'], unique=False, schema='hris')
    op.create_table('offices_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('offices_id', sa.Integer(), nullable=False),
    sa.Column('working_days', sa.JSON(), nullable=False),
    sa.Column('working_hours_start', sa.Time(), nullable=True),
    sa.Column('working_hours_end', sa.Time(), nullable=True),
    sa.Column('shift_type', sa.Enum('fixed', 'shift', 'flexible', 'full_24_7', name='shift_type_enum'), nullable=False),
    sa.Column('late_grace_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offices_id'], ['hris.offices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['hris.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='hris'
    )
    op.create_index(op.f('ix_hris_offices_policy_offices_id'), 'offices_policy', ['offices_id'], unique=True, schema='hris')
    op.create_index(op.f('ix_hris_offices_policy_organization_id'), 'offices_policy', ['organization_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_offices_policy_shift_type'), 'offices_policy', ['shift_type'], unique=False, schema='hris')
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('offices_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('shift_code', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('grace_before_minutes', sa.Integer(), nullable=False),
    sa.Column('grace_after_minutes', sa.Integer(), nullable=False),
    sa.Column('shift_type', sa.Enum('fixed', 'flexible', 'split', 'night', name='shift_type_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offices_id'], ['hris.offices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['hris.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='hris'
    )
    op.create_index(op.f('ix_hris_shift_id'), 'shift', ['id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_shift_offices_id'), 'shift', ['offices_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_shift_organization_id'), 'shift', ['organization_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_shift_shift_code'), 'shift', ['shift_code'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_shift_shift_type'), 'shift', ['shift_type'], unique=False, schema='hris')
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employees_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('checkin', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('checkout', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worked_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employees_id'], ['hris.employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['hris.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['hris.shift.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hris'
    )
    op.create_index(op.f('ix_hris_attendance_employees_id'), 'attendance', ['employees_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_attendance_id'), 'attendance', ['id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_attendance_organization_id'), 'attendance', ['organization_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_attendance_shift_id'), 'attendance', ['shift_id'], unique=False, schema='hris')
    op.create_table('leave_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('leave_types_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('allocated_days', sa.Integer(), nullable=False),
    sa.Column('used_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employment_id'], ['hris.employment_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_types_id'], ['hris.leave_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['hris.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='hris'
    )
    op.create_index(op.f('ix_hris_leave_balance_employment_id'), 'leave_balance', ['employment_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_leave_balance_id'), 'leave_balance', ['id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_leave_balance_leave_types_id'), 'leave_balance', ['leave_types_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_leave_balance_organization_id'), 'leave_balance', ['organization_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_leave_balance_year'), 'leave_balance', ['year'], unique=False, schema='hris')
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('leave_types_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='leave_request_status'), nullable=False),
    sa.Column('approved_by_employment_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_employment_id'], ['hris.employment_models.id'], ),
    sa.ForeignKeyConstraint(['employment_id'], ['hris.employment_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_types_id'], ['hris.leave_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['hris.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='hris'
    )
    op.create_index(op.f('ix_hris_leave_requests_approved_by_employment_id'), 'leave_requests', ['approved_by_employment_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_leave_requests_employment_id'), 'leave_requests', ['employment_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_leave_requests_id'), 'leave_requests', ['id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_leave_requests_leave_types_id'), 'leave_requests', ['leave_types_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_leave_requests_organization_id'), 'leave_requests', ['organization_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_leave_requests_status'), 'leave_requests', ['status'], unique=False, schema='hris')
    op.create_table('salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.Column('allowance', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employment_id'], ['hris.employment_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['hris.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='hris'
    )
    op.create_index(op.f('ix_hris_salaries_employment_id'), 'salaries', ['employment_id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_salaries_id'), 'salaries', ['id'], unique=False, schema='hris')
    op.create_index(op.f('ix_hris_salaries_organization_id'), 'salaries', ['organization_id'], unique=False, schema='hris')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hris_salaries_organization_id'), table_name='salaries', schema='hris')
    op.drop_index(op.f('ix_hris_salaries_id'), table_name='salaries', schema='hris')
    op.drop_index(op.f('ix_hris_salaries_employment_id'), table_name='salaries', schema='hris')
    op.drop_table('salaries', schema='hris')
    op.drop_index(op.f('ix_hris_leave_requests_status'), table_name='leave_requests', schema='hris')
    op.drop_index(op.f('ix_hris_leave_requests_organization_id'), table_name='leave_requests', schema='hris')
    op.drop_index(op.f('ix_hris_leave_requests_leave_types_id'), table_name='leave_requests', schema='hris')
    op.drop_index(op.f('ix_hris_leave_requests_id'), table_name='leave_requests', schema='hris')
    op.drop_index(op.f('ix_hris_leave_requests_employment_id'), table_name='leave_requests', schema='hris')
    op.drop_index(op.f('ix_hris_leave_requests_approved_by_employment_id'), table_name='leave_requests', schema='hris')
    op.drop_table('leave_requests', schema='hris')
    op.drop_index(op.f('ix_hris_leave_balance_year'), table_name='leave_balance', schema='hris')
    op.drop_index(op.f('ix_hris_leave_balance_organization_id'), table_name='leave_balance', schema='hris')
    op.drop_index(op.f('ix_hris_leave_balance_leave_types_id'), table_name='leave_balance', schema='hris')
    op.drop_index(op.f('ix_hris_leave_balance_id'), table_name='leave_balance', schema='hris')
    op.drop_index(op.f('ix_hris_leave_balance_employment_id'), table_name='leave_balance', schema='hris')
    op.drop_table('leave_balance', schema='hris')
    op.drop_index(op.f('ix_hris_attendance_shift_id'), table_name='attendance', schema='hris')
    op.drop_index(op.f('ix_hris_attendance_organization_id'), table_name='attendance', schema='hris')
    op.drop_index(op.f('ix_hris_attendance_id'), table_name='attendance', schema='hris')
    op.drop_index(op.f('ix_hris_attendance_employees_id'), table_name='attendance', schema='hris')
    op.drop_table('attendance', schema='hris')
    op.drop_index(op.f('ix_hris_shift_shift_type'), table_name='shift', schema='hris')
    op.drop_index(op.f('ix_hris_shift_shift_code'), table_name='shift', schema='hris')
    op.drop_index(op.f('ix_hris_shift_organization_id'), table_name='shift', schema='hris')
    op.drop_index(op.f('ix_hris_shift_offices_id'), table_name='shift', schema='hris')
    op.drop_index(op.f('ix_hris_shift_id'), table_name='shift', schema='hris')
    op.drop_table('shift', schema='hris')
    op.drop_index(op.f('ix_hris_offices_policy_shift_type'), table_name='offices_policy', schema='hris')
    op.drop_index(op.f('ix_hris_offices_policy_organization_id'), table_name='offices_policy', schema='hris')
    op.drop_index(op.f('ix_hris_offices_policy_offices_id'), table_name='offices_policy', schema='hris')
    op.drop_table('offices_policy', schema='hris')
    op.drop_index(op.f('ix_hris_employment_models_status'), table_name='employment_models', schema='hris')
    op.drop_index(op.f('ix_hris_employment_models_organization_id'), table_name='employment_models', schema='hris')
    op.drop_index(op.f('ix_hris_employment_models_manager_employment_id'), table_name='employment_models', schema='hris')
    op.drop_index(op.f('ix_hris_employment_models_id'), table_name='employment_models', schema='hris')
    op.drop_index(op.f('ix_hris_employment_models_employees_id'), table_name='employment_models', schema='hris')
    op.drop_table('employment_models', schema='hris')
    op.drop_index(op.f('ix_hris_offices_parent_id'), table_name='offices', schema='hris')
    op.drop_index(op.f('ix_hris_offices_organization_id'), table_name='offices', schema='hris')
    op.drop_index(op.f('ix_hris_offices_offices_type'), table_name='offices', schema='hris')
    op.drop_index(op.f('ix_hris_offices_is_active'), table_name='offices', schema='hris')
    op.drop_index(op.f('ix_hris_offices_id'), table_name='offices', schema='hris')
    op.drop_index(op.f('ix_hris_offices_code'), table_name='offices', schema='hris')
    op.drop_table('offices', schema='hris')
    op.drop_index(op.f('ix_hris_memberships_user_id'), table_name='memberships', schema='hris')
    op.drop_index(op.f('ix_hris_memberships_role'), table_name='memberships', schema='hris')
    op.drop_index(op.f('ix_hris_memberships_organization_id'), table_name='memberships', schema='hris')
    op.drop_index(op.f('ix_hris_memberships_is_active'), table_name='memberships', schema='hris')
    op.drop_table('memberships', schema='hris')
    op.drop_index(op.f('ix_hris_leave_types_organization_id'), table_name='leave_types', schema='hris')
    op.drop_index(op.f('ix_hris_leave_types_is_active'), table_name='leave_types', schema='hris')
    op.drop_index(op.f('ix_hris_leave_types_id'), table_name='leave_types', schema='hris')
    op.drop_index(op.f('ix_hris_leave_types_code'), table_name='leave_types', schema='hris')
    op.drop_table('leave_types', schema='hris')
    op.drop_index(op.f('ix_hris_invitations_email'), table_name='invitations', schema='hris')
    op.drop_table('invitations', schema='hris')
    op.drop_index(op.f('ix_hris_employees_position_organization_id'), table_name='employees_position', schema='hris')
    op.drop_index(op.f('ix_hris_employees_position_is_active'), table_name='employees_position', schema='hris')
    op.drop_index(op.f('ix_hris_employees_position_id'), table_name='employees_position', schema='hris')
    op.drop_table('employees_position', schema='hris')
    op.drop_table('employee_organizations', schema='hris')
    op.drop_index(op.f('ix_hris_audit_logs_id'), table_name='audit_logs', schema='hris')
    op.drop_index(op.f('ix_hris_audit_logs_created_at'), table_name='audit_logs', schema='hris')
    op.drop_table('audit_logs', schema='hris')
    op.drop_index(op.f('ix_hris_users_zitadel_id'), table_name='users', schema='hris')
    op.drop_table('users', schema='hris')
    op.drop_index(op.f('ix_hris_organizations_status'), table_name='organizations', schema='hris')
    op.drop_index(op.f('ix_hris_organizations_is_deleted'), table_name='organizations', schema='hris')
    op.drop_index(op.f('ix_hris_organizations_id'), table_name='organizations', schema='hris')
    op.drop_index(op.f('ix_hris_organizations_group_id'), table_name='organizations', schema='hris')
    op.drop_index(op.f('ix_hris_organizations_code'), table_name='organizations', schema='hris')
    op.drop_table('organizations', schema='hris')
    op.drop_index(op.f('ix_hris_employee_sensitive_tax_id'), table_name='employee_sensitive', schema='hris')
    op.drop_index(op.f('ix_hris_employee_sensitive_social_security_id'), table_name='employee_sensitive', schema='hris')
    op.drop_index(op.f('ix_hris_employee_sensitive_number_of_children'), table_name='employee_sensitive', schema='hris')
    op.drop_index(op.f('ix_hris_employee_sensitive_marital_status'), table_name='employee_sensitive', schema='hris')
    op.drop_index(op.f('ix_hris_employee_sensitive_identity_id'), table_name='employee_sensitive', schema='hris')
    op.drop_index(op.f('ix_hris_employee_sensitive_id'), table_name='employee_sensitive', schema='hris')
    op.drop_index(op.f('ix_hris_employee_sensitive_email'), table_name='employee_sensitive', schema='hris')
    op.drop_table('employee_sensitive', schema='hris')
    op.drop_index(op.f('ix_hris_organization_groups_status'), table_name='organization_groups', schema='hris')
    op.drop_index(op.f('ix_hris_organization_groups_is_active'), table_name='organization_groups', schema='hris')
    op.drop_index(op.f('ix_hris_organization_groups_id'), table_name='organization_groups', schema='hris')
    op.drop_index(op.f('ix_hris_organization_groups_code'), table_name='organization_groups', schema='hris')
    op.drop_table('organization_groups', schema='hris')
    op.drop_index(op.f('ix_hris_employees_status'), table_name='employees', schema='hris')
    op.drop_index(op.f('ix_hris_employees_joined_at'), table_name='employees', schema='hris')
    op.drop_index(op.f('ix_hris_employees_id'), table_name='employees', schema='hris')
    op.drop_index(op.f('ix_hris_employees_employee_number'), table_name='employees', schema='hris')
    op.drop_table('employees', schema='hris')
    # ### end Alembic commands ###
