"""update user table for authentik integration

Revision ID: aeed242c4a1e
Revises: 6bff4ea2a164
Create Date: 2026-05-05 04:34:24.834183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aeed242c4a1e'
down_revision: Union[str, Sequence[str], None] = '6bff4ea2a164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authentik_id', sa.String(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_users_deleted_at', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index('ix_users_locked_until', table_name='users')
    op.drop_index('ix_users_reset_token_expiry', table_name='users')
    op.drop_index('ix_users_reset_token_hash', table_name='users')
    op.create_index(op.f('ix_users_authentik_id'), 'users', ['authentik_id'], unique=True)
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'reset_token_expiry')
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'verified_at')
    op.drop_column('users', 'reset_token_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password_changed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('reset_token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('locked_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('failed_login_attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_authentik_id'), table_name='users')
    op.create_index('ix_users_reset_token_hash', 'users', ['reset_token_hash'], unique=False)
    op.create_index('ix_users_reset_token_expiry', 'users', ['reset_token_expiry'], unique=False)
    op.create_index('ix_users_locked_until', 'users', ['locked_until'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'authentik_id')
    # ### end Alembic commands ###
