"""msg

Revision ID: 059e85bdb588
Revises: a31026e652a0
Create Date: 2026-04-22 12:21:26.843771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '059e85bdb588'
down_revision: Union[str, Sequence[str], None] = 'a31026e652a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'terminated', 'suspended', name='employee_status'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('terminated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['employee.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=True)
    op.create_index(op.f('ix_employee_id'), 'employee', ['id'], unique=False)
    op.create_index(op.f('ix_employee_manager_id'), 'employee', ['manager_id'], unique=False)
    op.create_table('leave_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('requires_attachment', sa.Boolean(), nullable=True),
    sa.Column('max_days_per_year', sa.Integer(), nullable=True),
    sa.Column('max_consecutive_days', sa.Integer(), nullable=True),
    sa.Column('carry_forward_allowed', sa.Boolean(), nullable=True),
    sa.Column('carry_forward_limit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_emergency', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_leave_type_id'), 'leave_type', ['id'], unique=False)
    op.create_table('office',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('office_type', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['office.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_office_code'), 'office', ['code'], unique=True)
    op.create_index(op.f('ix_office_id'), 'office', ['id'], unique=False)
    op.create_table('employee_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(), nullable=True),
    sa.Column('reset_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_auth_employee_id'), 'employee_auth', ['employee_id'], unique=True)
    op.create_index(op.f('ix_employee_auth_is_active'), 'employee_auth', ['is_active'], unique=False)
    op.create_index(op.f('ix_employee_auth_locked_until'), 'employee_auth', ['locked_until'], unique=False)
    op.create_index(op.f('ix_employee_auth_reset_token'), 'employee_auth', ['reset_token'], unique=False)
    op.create_table('employee_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_position_id'), 'employee_position', ['id'], unique=False)
    op.create_table('leave_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('allocated_days', sa.Integer(), nullable=True),
    sa.Column('used_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_balance_id'), 'leave_balance', ['id'], unique=False)
    op.create_table('leave_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_request_employee_id'), 'leave_request', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_request_id'), 'leave_request', ['id'], unique=False)
    op.create_table('office_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('working_days', sa.JSON(), nullable=False),
    sa.Column('working_hours_start', sa.Time(), nullable=True),
    sa.Column('working_hours_end', sa.Time(), nullable=True),
    sa.Column('shift_type', sa.Enum('fixed', 'shift', 'flexible', 'full_24_7', name='shift_type_enum'), nullable=False),
    sa.Column('late_grace_minutes', sa.Integer(), nullable=True),
    sa.Column('overtime_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_office_policy_office_id'), 'office_policy', ['office_id'], unique=True)
    op.create_table('salary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_id'), 'salary', ['id'], unique=False)
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('shift_code', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=True),
    sa.Column('is_night_shift', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_id'), 'shift', ['id'], unique=False)
    op.create_index(op.f('ix_shift_office_id'), 'shift', ['office_id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('checkin', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('checkout', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worked_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_employee_id'), 'attendance', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_shift_id'), 'attendance', ['shift_id'], unique=False)
    op.create_table('employment_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'resigned', 'terminated', 'suspended', name='employment_status'), nullable=False),
    sa.Column('employment_type', sa.Enum('permanent', 'contract', 'intern', name='employment_type'), nullable=True),
    sa.Column('position_snapshot', sa.String(), nullable=True),
    sa.Column('office_snapshot', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['employee_position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employment_model_employee_id'), 'employment_model', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employment_model_id'), 'employment_model', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employment_model_id'), table_name='employment_model')
    op.drop_index(op.f('ix_employment_model_employee_id'), table_name='employment_model')
    op.drop_table('employment_model')
    op.drop_index(op.f('ix_attendance_shift_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_employee_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_shift_office_id'), table_name='shift')
    op.drop_index(op.f('ix_shift_id'), table_name='shift')
    op.drop_table('shift')
    op.drop_index(op.f('ix_salary_id'), table_name='salary')
    op.drop_table('salary')
    op.drop_index(op.f('ix_office_policy_office_id'), table_name='office_policy')
    op.drop_table('office_policy')
    op.drop_index(op.f('ix_leave_request_id'), table_name='leave_request')
    op.drop_index(op.f('ix_leave_request_employee_id'), table_name='leave_request')
    op.drop_table('leave_request')
    op.drop_index(op.f('ix_leave_balance_id'), table_name='leave_balance')
    op.drop_table('leave_balance')
    op.drop_index(op.f('ix_employee_position_id'), table_name='employee_position')
    op.drop_table('employee_position')
    op.drop_index(op.f('ix_employee_auth_reset_token'), table_name='employee_auth')
    op.drop_index(op.f('ix_employee_auth_locked_until'), table_name='employee_auth')
    op.drop_index(op.f('ix_employee_auth_is_active'), table_name='employee_auth')
    op.drop_index(op.f('ix_employee_auth_employee_id'), table_name='employee_auth')
    op.drop_table('employee_auth')
    op.drop_index(op.f('ix_office_id'), table_name='office')
    op.drop_index(op.f('ix_office_code'), table_name='office')
    op.drop_table('office')
    op.drop_index(op.f('ix_leave_type_id'), table_name='leave_type')
    op.drop_table('leave_type')
    op.drop_index(op.f('ix_employee_manager_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
