"""Add Employee Sensitive

Revision ID: 09407c1ed94a
Revises: 8e760b56ce4d
Create Date: 2026-04-25 11:17:15.819442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09407c1ed94a'
down_revision: Union[str, Sequence[str], None] = '8e760b56ce4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
