"""initial schema

Revision ID: 64fbfbe6b1ef
Revises: 2179c8e90164
Create Date: 2026-04-25 11:31:08.098739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64fbfbe6b1ef'
down_revision: Union[str, Sequence[str], None] = '2179c8e90164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_sensitive', sa.Column('social_security_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_employee_sensitive_social_security_id'), 'employee_sensitive', ['social_security_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_sensitive_social_security_id'), table_name='employee_sensitive')
    op.drop_column('employee_sensitive', 'social_security_id')
    # ### end Alembic commands ###
